---
- name: Deploy apache server
  hosts: web   # hosts is a ref to a host or hosts that may be resolved within the inventory
  gather_facts: no   # tells ansible to audit and define ansible_* vars (info about our hosts)
                     # the purpose is to make "intelligent" decisions via conditionals
  become: yes  # elevate priv -- because this is in the "play" section it will be passed to
               # ALL tasks

  tasks:

  # the package module tries to select
  # yum or apt or pkg5 (etc) automatically
  - name: latest Apache version installed
    package:
      name: apache2
      state: latest   # IF state is an option, you should ALWAYS have it mentioned within your
                      # playbook, even if it has a default!!!

  - name: Apache enabled and running
    service:
      name: apache2
      enabled: yes
      state: started

  # Copy index.html into the service
  - name: copy index.html
    copy:
      src: ~/ans/files/index.html
      dest: /var/www/html/
    notify: restart_apache

  # THIS IS THE WAY TO COPY CONTENT TO A FILE
  #- name: copy content to our new file
  #  copy:
  #    content: "{{ myvar }}"
  #    dest: file.txt

  # example of writing variable values / content out to a file
  #- name: write out content to a file
  #  shell: echo {{ myvar }} >> file.txt
  #  changed_when: 

  # if dest is directory download every time
  # but only replace if destination is different
  - name: Download a copy of apache2.conf
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/rzfeeser/alta3files/master/apache2.conf
      dest: /etc/apache2/
    notify: restart_apache   # this is a CALL to a hanlder named "restart_apache"

  handlers:
  - name: restart_apache
    service:
      name: apache2
      state: restarted
