---
- name: Loop across the following (think "one at a time")
  block:
    - name: CHANGE - Create filesystem with quota for teachers
      dellemc.isilon.dellemc_isilon_filesystem:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ isilon_port }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ item.pass }}"
        path: "{{ base_path }}/teachers/{{ item.name }}"
        owner:
            name: "root"
            provider_type: "file"
        access_control: "{{ access_control }}"
        recursive: true
        state: "{{ state }}"
        
  rescue:
    - name: CATCHING SINGLE FAILURE - a single failure occured within the change loop
      lineinfile:
        path: isilon_failure_teachers.txt
        backup: yes
        create: yes
        state: present
        line: "{{ item }}"